---
- name: Login to ACR
  ansible.builtin.command:
    docker login {{ acr_login_url }} -u {{ acr_username }} -p{{ acr_password }}

- name: Pull nginx from docker library
  ansible.builtin.docker_image:
    name: docker.io/nginx:latest
    source: pull

- name: Tag image
  ansible.builtin.command:
    docker tag nginx:latest {{ acr_login_url }}/nginx:latest

- name: Clone my app
  ansible.builtin.git:
    name: https://github.com/dev-alex-ops/postgen
    clone: yes
    dest: ../customApp

- name: Build dockerfile
  community.docker.docker_image_build:
    name: "{{ acr_login_url }}/postgen:v0.0.1"
    path: ../customApp
    dockerfile: Dockerfile
      
- name: Push nginx image to ACR
  community.docker.docker_image_push:
    name: "{{ acr_login_url }}/postgen"
    tag: v0.0.1
    
- name: Push custom app to ACR
  community.docker.docker_image_push:
    name: "{{ acr_login_url }}/nginx:latest"
    tag: latest