---
- name: Setup ACR and images 
  hosts: localhost
  vars_files: 
    - secrets.yml
  tasks:
    - name: Pull, build, tag and push images to ACR
      include_role:
        name: acr

- name: Setup Webserver
  hosts: webapp
  vars_files: 
    - secrets.yml
  tasks:
    - name: Configure VM with Podman and deploy web server
      include_role:
        name: vm

- name: Setup AKS
  hosts: localhost
  vars_files: 
    - secrets.yml
  tasks:
    - name: Deploy app to AKS
      include_role:
        name: aks
      